name: Publish Docker image (server-info)

on:
  workflow_dispatch:
    inputs:
      dir:
        description: 'Directory'
        required: true
      tag:
        description: 'Image tag'
        required: true

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: ./${{ github.event.inputs.dir }}/Dockerfile
          context: ./${{ github.event.inputs.dir }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          repository: subicura/${{ github.event.inputs.dir }}
          tags: subicura/${{ github.event.inputs.dir }}:${{ github.event.inputs.tag }}